# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('tentativas', models.IntegerField()),
                ('frustrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Toques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('t', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='toques',
            field=models.ManyToManyField(to='app.Toques'),
        ),
    ]
