# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160505_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='toques',
        ),
        migrations.AddField(
            model_name='toques',
            name='jogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Jogo'),
            preserve_default=False,
        ),
    ]
